### ISSUE TITLE
Implement Gradle Build Tool

### ISSUE THREAD

**Issue by DaleMorris2021** [IUS-CS/c346-fa23-project-team-rocket#12]
Implement a Gradle-based build system for reproduceable dependencies and builds.

**Comment by Xavbeat03** [comment]
Had to install SDKMan for this.

**Comment by Xavbeat03** [comment]
After using the gradle install daemon for the wrapper it was pretty simple, also did some light configuration for our project to make things simpler later on.

**Comment by Xavbeat03** [comment]
#21 This is the pull request.

**Comment by Xavbeat03** [comment]
Just needs to be reviewed now. Plus any fixes that may be needed.
