### ISSUE TITLE
Grass class

### ISSUE THREAD

**Issue by DaleMorris2021** [IUS-CS/c346-fa23-project-team-rocket#17]
Grass acts as a basic food source for rabbits. It should grow daily.

**Comment by Xavbeat03** [comment]
Rabbits also need the ability to eat grass
Grass should have a chance to create another grass in an empty space in the 8 spaces around it.
Should be a derivative of abstract organism
Needs a die() method, and a breed() method
Some sort of boolean is required to stop them from infinitely breeding.
A method for newday should be made to set the grass breeding status, and new grass shouldn't be able to breed.
